FROM python:3.12.3-alpine3.19

WORKDIR /usr/share/src 

COPY /requirements.txt  ./requirements.txt 
RUN  pip install -r ./requirements.txt 

COPY /src ./  


ENV PYTHONBUFFERED 1 

ENTRYPOINT [ "python3","-u", "main"] 

#ENTRYPOINT [ "python3","-u", "compose_app"] 
#CMD ["echo"]
 